### ISSUE TITLE
It creates a nice graphical representation of even a larger JSON File

### ISSUE THREAD

**Issue by PeterLo63** [mohitkumartoshniwal/jsonlens#5]
It took me a moment to understand how to actually do something with it - but when I got my JSON file (>250kB Text) opened in it, it actually presented very quickly a nice Object diagram of it.

I have yet not found any way to get the graphical representation out, so one could make use of it, but the representation is nice.
An export possibility to some Image, SVG  or PDF format would be on my wishlist

**Comment by mohitkumartoshniwal** [comment]
Currently one can download the representation in the form of images with support for svg, png and jpeg. svg export may be a little buggy. And not sure whether pdf exports would make sense for the representation. 

Hence closing this issue for now. But if there is still any interest for pdf export maybe another issue can be created later on.
